### ISSUE TITLE
完全不工作呢…

### ISSUE THREAD

**Issue by oTnTh** [violet1986/ffxivapp-plugin-itemdb#2]
国服当前版本。装上以后不管是手工点击设置里的按钮，或者尝试记录雇员物品均告失败，无论是输入物品的部分或完整名称，都没有返回任何结果。

丢着没管几天后发现，FFXIVAPP\Plugins\FFXIVAPP.Plugin.ItemDB\DescFiles\Users下多出两个文件来。一个是我的角色名，一个是另外一个账号下的角色名，其中有数据，但我的角色物品数据仍然不正确。

求正确的使用姿势…

**Comment by violet2016** [comment]
请问ffxivapp和itemdb都是什么版本呢

**Comment by violet2016** [comment]
ffxivapp最新版本是3.0.5592.38336, itemdb请使用1.0.1.6，如果版本不对应可能会发生莫名其妙的问题，如果还不行请加我qq：929534464，谢谢使用(^o^)/~

**Comment by oTnTh** [comment]
原本想说我打开了自动更新，所以本体和插件都肯定是最新版本的。不过为了确认，干脆将FFXIVAPP整个重装了一下，结果竟然就好了，完全没闹明白究竟发生了什么… =。=

以下顺便提一点建议的说：

一、整个插件的按钮完全没交互是不是不大好，比如按了纪录雇员1物品按钮和设置中的刷新按钮都是完全没反馈的，数据读取成功了失败了用户也完全不知道。其实我觉得最好是有个console区域，把读取操作加上时间戳都写进去，假如日后需要debug反馈什么的也有信息可以提交。

二、既然角色id是可以提取的，那雇员id应该也是可以提取的吧？如果都可以，那是不是其实并不需要手动刷新雇员物品数据，根据角色id和雇员id自动纪录是否可行？

三、搜索结果不支持反白，不支持鼠标滚轮，不支持点击排序，用起来有点不方便的说。实际上我觉得一次性把所有物品的信息都显示出来，搜索功能改成过滤可能会更直观一点，如果性能方面的代价不大的话。（btw，要求支持拼音首字母查询会不会有点过分…）

**Comment by violet2016** [comment]
雇员的名字的确没法提取，因为都是临时从服务器得到的数据，内存中的位置不确定，现在作者增加了网络包的读取，可能有新的方法，还没来得及调研。
ui的确不太友好，你的建议非常好，我抽空就改进下，感谢
